version: '{branch}-{build}'

os:
- Visual Studio 2017

services:
- postgresql96

configuration:
- Release
- Debug

environment:
  PGUSER: postgres
  PGPASSWORD: Password12!
  matrix:
    - GENERATOR: Visual Studio 15 2017 Win64

init: []

install: []

before_build:
- if defined BINDIR (set "PATH=%BINDIR%;%PATH:C:\Program Files\Git\usr\bin;=%")
- md build
- cd build
- cmake -Wno-dev --config "%CONFIGURATION%" -G "%GENERATOR%" ..

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
- ctest -C "%CONFIGURATION%" --output-on-failure
